name: Git Clean
description: Overrides the git clean flags for a job.
author: https://github.com/buildkite
requirements: []
configuration:
  properties:
    flags:
      type: string
    skip_on_retry:
      type: boolean
    additionalProperties: false
  required:
    - flags
